# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Install Sitecore CLI
  inputs:
    command: custom
    custom: tool
    arguments: restore
- task: DotNetCoreCLI@2
  displayName: Initialise CLI Plugins
  inputs:
    command: 'custom'
    custom: 'sitecore'
    arguments: '--help'
- task: DotNetCoreCLI@2
  displayName: Authenticate with XM-C Deploy Application
  inputs:
    command: 'custom'
    custom: 'sitecore cloud login'
    arguments: '--client-credentials --client-id $(XM_CLOUD_CLIENT_ID) --client-secret $(XM_CLOUD_CLIENT_SECRET) --allow-write'